# Generated by Django 4.1.6 on 2023-02-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='showDepartamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartamentoID', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='showEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoID', models.IntegerField()),
                ('Estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'EstadosEmpleado',
            },
        ),
        migrations.CreateModel(
            name='showJefes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpleadoID', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('SucursalID', models.IntegerField()),
                ('PuestoID', models.IntegerField()),
                ('PuestoTexto', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='showPuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PuestoID', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('DepartamentoID', models.IntegerField()),
            ],
            options={
                'db_table': 'Puestos',
            },
        ),
    ]
