# Generated by Django 4.1.6 on 2023-02-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='showEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpleadoID', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('SucursalID', models.IntegerField()),
                ('PuestoID', models.IntegerField()),
                ('PuestoTexto', models.CharField(max_length=200)),
                ('NombreCompleto', models.CharField(default=None, max_length=200)),
                ('Sucursal', models.CharField(default=None, max_length=100)),
                ('Identificacion', models.CharField(default=None, max_length=100)),
                ('ReportaA', models.IntegerField(default=None)),
                ('TelefonoCelular', models.CharField(default=None, max_length=100)),
                ('TelefonoTrabajo', models.CharField(default=None, max_length=100)),
                ('Direccion', models.CharField(default=None, max_length=150)),
                ('Genero', models.CharField(default=None, max_length=15)),
                ('FechaNacimiento', models.CharField(default=None, max_length=100)),
                ('FechaAlta', models.CharField(default=None, max_length=100)),
                ('FechaBaja', models.CharField(default=None, max_length=100)),
                ('EstadoID', models.IntegerField(default=None)),
                ('Estado', models.CharField(default=None, max_length=100)),
                ('Notas', models.TextField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
        migrations.DeleteModel(
            name='showJefes',
        ),
    ]
