# Generated by Django 4.1.6 on 2023-02-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_showempleados_apellidos_showempleados_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='showempleados',
            name='DepartamentoID',
            field=models.IntegerField(default=None),
        ),
    ]
