USE [PoMoMin]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TABLE [dbo].[EstadosUsuario](
	[EstadoID] [int] IDENTITY(1,1) NOT NULL,
	[Estado] [nvarchar](100) NOT NULL,
	[Descripcion] [nvarchar](150) NULL
 CONSTRAINT [PK_ESTADOSUSUARIO] PRIMARY KEY CLUSTERED 
(
	[EstadoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[PerfilesUsuario] (
    PerfilID [int] IDENTITY(1,1) NOT NULL,
    NombrePerfil [nvarchar](100) NOT NULL,
    Descripcion [nvarchar](150) NULL
 CONSTRAINT [PK_PERFILESUSUARIO] PRIMARY KEY CLUSTERED 
(
	[PerfilID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO



CREATE TABLE [dbo].[Usuarios] (
    UsuarioID [int] IDENTITY(1,1) NOT NULL,
    Usuario [nvarchar](200) NOT NULL,
    Clave [nvarchar](300) NOT NULL,
    PerfilID [int] NOT NULL,
    FechaCreacion [date] DEFAULT GETDATE(),
    FechaUltimaActualizacion [date] NULL,
    EstadoID [int] NOT NULL,
 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	UsuarioID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE dbo.USUARIOS
ADD CONSTRAINT FK_PERFILES_USUARIOS
FOREIGN KEY (PerfilID)
REFERENCES dbo.PerfilesUsuario (PerfilID);

ALTER TABLE dbo.USUARIOS
ADD CONSTRAINT FK_ESTADOS_USUARIOS
FOREIGN KEY (EstadoID)
REFERENCES dbo.EstadosUsuario (EstadoID);

GO



CREATE TABLE dbo.Bitacora (
    NoRegistro [bigint] IDENTITY(1,1) NOT NULL,
    Usuario [nvarchar](100) NOT NULL,
    FechaHoraEvento [datetime] DEFAULT GETDATE(),
    TipoEvento [nvarchar](50),
    EstadoEvento [nvarchar](50),
    Descripcion [nvarchar](250),
    Dispositivo [nvarchar](200),
 CONSTRAINT [PK_BITACORA] PRIMARY KEY CLUSTERED 
(
	NoRegistro ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE NONCLUSTERED INDEX NCI_USUARIO
ON BITACORA(Usuario ASC); 

CREATE NONCLUSTERED INDEX NCI_TIPO_EVENTO
ON BITACORA(TipoEvento ASC); 

CREATE NONCLUSTERED INDEX NCI_ESTADO_EVENTO
ON BITACORA(EstadoEvento ASC); 

CREATE NONCLUSTERED INDEX NCI_DISPOSITIVO
ON BITACORA(Dispositivo ASC); 

GO