# Generated by Django 4.1.6 on 2023-02-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='showCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoriaID', models.IntegerField()),
                ('Categoria', models.CharField(max_length=100)),
                ('AplicaA', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Categorias',
            },
        ),
    ]
