# Generated by Django 4.1.6 on 2023-02-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_showfabricantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='showEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoID', models.IntegerField()),
                ('Estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'EstadosInventario',
            },
        ),
        migrations.CreateModel(
            name='showProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProveedorID', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('Activo', models.IntegerField()),
            ],
            options={
                'db_table': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='showSucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SucursalID', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('Activo', models.IntegerField()),
            ],
            options={
                'db_table': 'Sucursales',
            },
        ),
    ]
