# Generated by Django 4.1.6 on 2023-02-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_showestados_showproveedores_showsucursales'),
    ]

    operations = [
        migrations.CreateModel(
            name='showInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InventarioID', models.IntegerField()),
                ('CodigoInventario', models.CharField(max_length=100)),
                ('Categoria', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Serie', models.CharField(max_length=100)),
                ('Fabricante', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Inventario',
            },
        ),
    ]
