# Generated by Django 4.1.6 on 2023-02-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_showinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='showinventario',
            name='AsignadoA',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='showinventario',
            name='CodigoBarra',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='showinventario',
            name='Descripcion',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='showinventario',
            name='EstadoID',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='showinventario',
            name='FechaCompra',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='showinventario',
            name='FechaUltimoSoporte',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='showinventario',
            name='FechaUtilMaxima',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='showinventario',
            name='Notas',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='showinventario',
            name='ProveedorID',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='showinventario',
            name='SucursalID',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='showinventario',
            name='TipoInventarioID',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='showinventario',
            name='CodigoInventario',
            field=models.CharField(max_length=200),
        ),
    ]
