# Generated by Django 4.1.6 on 2023-02-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_showinventario_asignadoa_showinventario_codigobarra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showinventario',
            name='CategoriaID',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='showinventario',
            name='FabricanteID',
            field=models.IntegerField(default=None),
        ),
    ]
