# Generated by Django 4.1.6 on 2023-02-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_showinventario_categoriaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showinventario',
            name='Sucursal',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
