# Generated by Django 4.1.6 on 2023-02-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_showinventario_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='showinventario',
            name='Estado',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
