# Generated by Django 4.1.6 on 2023-02-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_showinventario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='showinventario',
            name='AsignadoNombre',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
