# Generated by Django 4.1.6 on 2023-03-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_showinventario_asignadonombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='showMotivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MotivoID', models.IntegerField()),
                ('Motivo', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=200)),
                ('AplicaA', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'MotivosCambio',
            },
        ),
    ]
