# Generated by Django 4.1.6 on 2023-03-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_showmotivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='showfabricantes',
            name='Descripcion',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='showproveedores',
            name='Descripcion',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='showproveedores',
            name='Direccion',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='showproveedores',
            name='FechaRegistro',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='showproveedores',
            name='NombreContacto',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='showproveedores',
            name='Notas',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='showproveedores',
            name='Telefono',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='showsucursales',
            name='Direccion',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
