# Generated by Django 4.1.6 on 2023-03-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_showfabricantes_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='showHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InventarioID', models.IntegerField()),
                ('EmpleadoID', models.IntegerField()),
                ('MotivoAsignacionID', models.IntegerField()),
                ('MotivoDesasignacionID', models.IntegerField()),
                ('FechaVigente', models.CharField(default=None, max_length=100)),
                ('FechaFin', models.CharField(default=None, max_length=100)),
                ('Notas', models.TextField(default=None)),
                ('CodigoInventario', models.CharField(max_length=200)),
                ('NombreCompleto', models.CharField(max_length=200)),
                ('MotivoAsignacion', models.CharField(default=None, max_length=200)),
                ('MotivoDesasignacion', models.CharField(default=None, max_length=200)),
            ],
            options={
                'db_table': 'InventarioEmpleados',
            },
        ),
    ]
