USE PoMoMin
GO

CREATE PROCEDURE DEACTIVATE_INVENTARIO
	@ID BIGINT,
	@IDESTADO INT,
	-- DATOS PARA BITACORA
	@USUARIOBITA NVARCHAR(100),
	@DISPOSITIVO NVARCHAR(200),
	-- RECUPERAR RESULTADO
	@RESULT BIGINT OUTPUT
AS
DECLARE @MENSAJE AS VARCHAR(100);
BEGIN TRY
	IF @ID IS NULL OR @IDESTADO IS NULL
	   BEGIN
			RAISERROR('Algunos parámetros no pueden ser nulos', 16, 1)
			SET @RESULT = 0;
		END
		-- DESASIGNAR EL INVENTARIO DE LOS EMPLEADOS
		-- HISTORICO
		UPDATE InventarioEmpleados
		SET FechaFin = GETDATE(),
			MotivoDesasignacionID = 8, -- DESTRUCCION O PERDIDA TOTAL DE INVENTARIO
			Notas = 'Se desasignó el equipo por actualización del estado del inventario'
		WHERE InventarioID = @ID AND FechaFin IS NULL

		-- DESASIGNAR Y MARCAR COMO INACTIVO
		UPDATE Inventario
		SET AsignadoA = NULL,
			EstadoID = @IDESTADO
		WHERE InventarioID = @ID

		SET @MENSAJE = 'Desactivación de inventario con ID: ' + CAST(@ID AS VARCHAR);
		-- BITACORA
		EXEC INSERT_BITACORA @USUARIOBITA, 'DEACTIVATE', 'COMPLETADO EXITOSAMENTE', @MENSAJE, @DISPOSITIVO;

	SET @RESULT = 1;
END TRY
BEGIN CATCH
	SET @MENSAJE = 'Mensaje de error:' + ERROR_MESSAGE();
	EXEC INSERT_BITACORA @USUARIOBITA, 'DEACTIVATE', 'NO COMPLETADO', @MENSAJE, @DISPOSITIVO;
	SET @RESULT = 0;
END CATCH
GO