USE PoMoMin
GO

CREATE PROCEDURE DEACTIVATE_EMPLEADO
	@ID BIGINT,
	@IDESTADO INT,
	-- DATOS PARA BITACORA
	@USUARIOBITA NVARCHAR(100),
	@DISPOSITIVO NVARCHAR(200),
	-- RECUPERAR RESULTADO
	@RESULT BIGINT OUTPUT
AS
DECLARE @MENSAJE AS VARCHAR(100);
BEGIN TRY
	IF @ID IS NULL OR @IDESTADO IS NULL
	BEGIN
		RAISERROR('Algunos parámetros no pueden ser nulos', 16, 1)
		SET @RESULT = 0;
	END
	-- PONER EL EMPLEADO COMO DE BAJA Y MARCAR COMO INACTIVO
	UPDATE Empleados
	SET FechaBaja = GETDATE(),
		EstadoID = 2
	WHERE EmpleadoID = @ID

	-- LIBERAR TODO EL INVENTARIO QUE SE HABIA ASIGNADO A ESE EMPLEADO
	UPDATE Inventario
	SET AsignadoA = NULL
	WHERE AsignadoA = @ID

	-- MARCAR EL INVENTARIO EN EL HISTORICO COMO DISPONIBLE POR MOTIVO DE DESACTIVACION DE EMPLEADO
	UPDATE InventarioEmpleados
	SET FechaFin = GETDATE(),
		MotivoDesasignacionID = 9
	WHERE EmpleadoID = @ID AND FechaFin IS NULL

	SET @MENSAJE = 'Desactivación de empleado con ID: ' + CAST(@ID AS VARCHAR);
	-- BITACORA
	EXEC INSERT_BITACORA @USUARIOBITA, 'DEACTIVATE', 'COMPLETADO EXITOSAMENTE', @MENSAJE, @DISPOSITIVO;
	SET @RESULT = 1;
END TRY
BEGIN CATCH
	SET @MENSAJE = 'Mensaje de error:' + ERROR_MESSAGE();
	EXEC INSERT_BITACORA @USUARIOBITA, 'DEACTIVATE', 'NO COMPLETADO', @MENSAJE, @DISPOSITIVO;
	SET @RESULT = 0;
END CATCH
GO