USE PoMoMin
GO

CREATE PROCEDURE INSERT_BITACORA
	@USUARIO NVARCHAR(100),
	@TIPO NVARCHAR(50),
	@ESTADO NVARCHAR(50),
	@DECRIPCION NVARCHAR(250),
	@DISPOSITIVO NVARCHAR(200)
AS
BEGIN TRY
	INSERT INTO Bitacora(Usuario, TipoEvento, EstadoEvento, Descripcion, Dispositivo)
	VALUES(@USUARIO, @TIPO, @ESTADO, @DECRIPCION, @DISPOSITIVO);

	PRINT 'Registro insertado correctamente'
END TRY
BEGIN CATCH
	PRINT 'Se ha producido el error: ' + ERROR_MESSAGE()
END CATCH
GO