USE PoMoMin
GO

CREATE PROCEDURE INSERT_PROVEEDOR
	@NOMBRE NVARCHAR(100),
	@DESCRIPCION NVARCHAR(150),
	@DIRECCION NVARCHAR(150),
	@TELEFONO NVARCHAR(100),
	@NOMBRECONTACTO NVARCHAR(100),
	-- @FECHAREGISTRO DEFAULT GETDATE() DESDE CREACION DE TABLA
	@NOTAS NTEXT,
	-- DATOS PARA BITACORA
	@USUARIOBITA NVARCHAR(100),
	@DISPOSITIVO NVARCHAR(200),
	-- RECUPERAR ID
	@ID INT OUTPUT
AS
DECLARE @MENSAJE AS VARCHAR(100);
BEGIN TRY
	IF @NOMBRE IS NULL OR @DIRECCION IS NULL OR @TELEFONO IS NULL OR @NOMBRECONTACTO IS NULL
	   BEGIN
			RAISERROR('Algunos parámetros no pueden ser nulos', 16, 1)
		END
	INSERT INTO Proveedores(Nombre, Descripcion, Direccion, Telefono, NombreContacto, Activo, Notas)
	VALUES(@NOMBRE, @DESCRIPCION, @DIRECCION, @TELEFONO, @NOMBRECONTACTO, 1, @NOTAS);
		   SET @ID = @@IDENTITY;

	SET @MENSAJE = 'Inserción de proveedor con ID: ' + CAST(@ID AS VARCHAR);

	-- BITACORA
	EXEC INSERT_BITACORA @USUARIOBITA, 'INSERT', 'COMPLETADO EXITOSAMENTE', @MENSAJE, @DISPOSITIVO;

	PRINT 'Registro insertado correctamente'
END TRY
BEGIN CATCH
	SET @MENSAJE = 'Mensaje de error:' + ERROR_MESSAGE();
	EXEC INSERT_BITACORA @USUARIOBITA, 'INSERT', 'NO COMPLETADO', @MENSAJE, @DISPOSITIVO;
END CATCH
GO