USE PoMoMin
GO

CREATE PROCEDURE INSERT_INVENTARIO
	@CODIGOLETRAS NVARCHAR(200),
	@CODIGOBARRA NVARCHAR(200),
	@IDTIPO INT,
	@IDCATEGORIA INT,
	@IDFABRICANTE INT,
	@MODELO NVARCHAR(50),
	@SERIE NVARCHAR(50),
	@DESCRIPCION NVARCHAR(150),
	@IDSUCURSAL INT,
	@IDPROVEEDOR INT,
	@IDESTADO INT,
	@FECHACOMPRA DATE,
	@FECHAUTILMAXIMA DATE,
	@FECHAULTIMOSOPORTE DATE,
	-- @FECHAREGISTRO DEFAULT GETDATE() DESDE CREACION DE TABLA
	@NOTAS NTEXT,
	-- DATOS PARA BITACORA
	@USUARIOBITA NVARCHAR(100),
	@DISPOSITIVO NVARCHAR(200),
	-- RECUPERAR ID
	@ID BIGINT OUTPUT
AS
DECLARE @MENSAJE AS VARCHAR(100);
BEGIN TRY
	IF @CODIGOLETRAS IS NULL OR @CODIGOBARRA IS NULL OR @IDTIPO IS NULL OR @IDCATEGORIA IS NULL OR @IDFABRICANTE IS NULL
	   OR @IDSUCURSAL IS NULL OR @IDPROVEEDOR IS NULL OR @IDESTADO IS NULL
	   BEGIN
			RAISERROR('Algunos parámetros no pueden ser nulos', 16, 1)
			SET @ID = 0;
		END
	IF EXISTS(SELECT CodigoInventario FROM Inventario WHERE CodigoInventario = @CODIGOLETRAS)
	   BEGIN
			RAISERROR('El código alfanumerico ya existe en la base', 16, 1)
			SET @ID = 0;
		END
	IF EXISTS(SELECT CodigoBarra FROM Inventario WHERE CodigoBarra = @CODIGOBARRA)
	   BEGIN
			RAISERROR('El código de barras o qr ya existe en la base', 16, 1)
			SET @ID = 0;
		END
	INSERT INTO Inventario(CodigoInventario, CodigoBarra, TipoInventarioID, CategoriaID, FabricanteID, Modelo, Serie, Descripcion, 
	SucursalID, ProveedorID, EstadoID, FechaCompra, FechaUtilMaxima, FechaUltimoSoporte, Notas)
	VALUES(@CODIGOLETRAS, @CODIGOBARRA, @IDTIPO, @IDCATEGORIA, @IDFABRICANTE, @MODELO, @SERIE, @DESCRIPCION, 
		   @IDSUCURSAL, @IDPROVEEDOR, @IDESTADO, @FECHACOMPRA, @FECHAUTILMAXIMA, @FECHAULTIMOSOPORTE, @NOTAS);
		   SET @ID = @@IDENTITY;

	SET @MENSAJE = 'Inserción de inventario con ID: ' + CAST(@ID AS VARCHAR);

	-- BITACORA
	EXEC INSERT_BITACORA @USUARIOBITA, 'INSERT', 'COMPLETADO EXITOSAMENTE', @MENSAJE, @DISPOSITIVO;

	PRINT 'Registro insertado correctamente'
	SET @ID = 1;
END TRY
BEGIN CATCH
	SET @MENSAJE = 'Mensaje de error:' + ERROR_MESSAGE();
	EXEC INSERT_BITACORA @USUARIOBITA, 'INSERT', 'NO COMPLETADO', @MENSAJE, @DISPOSITIVO;
	SET @ID = 0;
END CATCH
GO