USE PoMoMin
GO

CREATE PROCEDURE UPDATE_SUCURSAL
	@ID INT,
	@NOMBRE NVARCHAR(100),
	@DIRECCION NVARCHAR(200),
	@ACTIVO BIT,
	-- DATOS PARA BITACORA
	@USUARIOBITA NVARCHAR(100),
	@DISPOSITIVO NVARCHAR(200)
AS
DECLARE @MENSAJE AS VARCHAR(100);
BEGIN TRY
	IF @ID IS NULL OR @ACTIVO IS NULL
	   BEGIN
			RAISERROR('Algunos parámetros no pueden ser nulos', 16, 1)
		END
	UPDATE Sucursales
	SET Nombre = COALESCE(@NOMBRE, Nombre),
		Direccion = COALESCE(@DIRECCION, Direccion),
		Activo = COALESCE(@ACTIVO, Activo)
	WHERE SucursalID = @ID
	
	IF @ACTIVO <> 0 -- INACTIVO
	BEGIN
		SET @MENSAJE = 'Actualización de sucursal con ID: ' + CAST(@ID AS VARCHAR);
		-- BITACORA
		EXEC INSERT_BITACORA @USUARIOBITA, 'UPDATE', 'COMPLETADO EXITOSAMENTE', @MENSAJE, @DISPOSITIVO;
	END
	ELSE
	BEGIN
		SET @MENSAJE = 'Desactivación de sucursal con ID: ' + CAST(@ID AS VARCHAR);
		-- BITACORA
		EXEC INSERT_BITACORA @USUARIOBITA, 'DEACTIVATE', 'COMPLETADO EXITOSAMENTE', @MENSAJE, @DISPOSITIVO;
	END

END TRY
BEGIN CATCH
	SET @MENSAJE = 'Mensaje de error:' + ERROR_MESSAGE();
	EXEC INSERT_BITACORA @USUARIOBITA, 'UPDATE', 'NO COMPLETADO', @MENSAJE, @DISPOSITIVO;
END CATCH
GO