USE PoMoMin
GO

CREATE PROCEDURE UPDATE_PROVEEDOR
	@ID BIGINT,
	@NOMBRE NVARCHAR(100),
	@DESCRIPCION NVARCHAR(150),
	@DIRECCION NVARCHAR(150),
	@TELEFONO NVARCHAR(100),
	@NOMBRECONTACTO NVARCHAR(100),
	@ACTIVO BIT,
	-- @FECHAREGISTRO DEFAULT GETDATE() DESDE CREACION DE TABLA
	@NOTAS NTEXT,
	-- DATOS PARA BITACORA
	@USUARIOBITA NVARCHAR(100),
	@DISPOSITIVO NVARCHAR(200),
	-- RECUPERAR RESULTADO
	@RESULT BIGINT OUTPUT
AS
DECLARE @MENSAJE AS VARCHAR(100);
BEGIN TRY
	IF @ID IS NULL OR @ACTIVO IS NULL
	   BEGIN
			RAISERROR('Algunos parámetros no pueden ser nulos', 16, 1)
			SET @RESULT = 0;
		END
	UPDATE Proveedores
	SET Nombre = COALESCE(@NOMBRE, Nombre),
		Descripcion = COALESCE(@DESCRIPCION, Descripcion),
		Direccion = COALESCE(@DIRECCION, Direccion),
		Telefono = COALESCE(@TELEFONO, Telefono),
		NombreContacto = COALESCE(@NOMBRECONTACTO, NombreContacto),
		Activo = COALESCE(@ACTIVO, Activo),
		Notas = COALESCE(@NOTAS, Notas)
	WHERE ProveedorID = @ID
	
	IF @ACTIVO <> 0 -- INACTIVO
	BEGIN
		SET @MENSAJE = 'Actualización de proveedor con ID: ' + CAST(@ID AS VARCHAR);
		-- BITACORA
		EXEC INSERT_BITACORA @USUARIOBITA, 'UPDATE', 'COMPLETADO EXITOSAMENTE', @MENSAJE, @DISPOSITIVO;
	END
	ELSE
	BEGIN
		SET @MENSAJE = 'Desactivación de proveedor con ID: ' + CAST(@ID AS VARCHAR);
		-- BITACORA
		EXEC INSERT_BITACORA @USUARIOBITA, 'DEACTIVATE', 'COMPLETADO EXITOSAMENTE', @MENSAJE, @DISPOSITIVO;
	END
	SET @RESULT = 1;
END TRY
BEGIN CATCH
	SET @MENSAJE = 'Mensaje de error:' + ERROR_MESSAGE();
	EXEC INSERT_BITACORA @USUARIOBITA, 'UPDATE', 'NO COMPLETADO', @MENSAJE, @DISPOSITIVO;
	SET @RESULT = 0;
END CATCH
GO