USE PoMoMin
GO

CREATE PROCEDURE UPDATE_USUARIO
	@ID INT,
	@CLAVEBASE64 NVARCHAR(300),
	@IDPERFIL INT,
	-- @FECHAREGISTRO DEFAULT GETDATE() DESDE CREACION DE TABLA
	-- @FECHAULTIMAACTUALIZACION SE ASIGNA DIRECTAMENTE DENTRO DEL PROCEDIMIENTO
	@ESTADOID INT,
	-- DATOS PARA BITACORA
	@USUARIOBITA NVARCHAR(100),
	@DISPOSITIVO NVARCHAR(200),
	-- RECUPERAR RESULTADO
	@RESULT BIGINT OUTPUT
AS
DECLARE @MENSAJE AS VARCHAR(100);
BEGIN TRY
	IF @ID IS NULL OR @ESTADOID IS NULL
	   BEGIN
			RAISERROR('Algunos parámetros no pueden ser nulos', 16, 1)
			SET @RESULT = 0;
		END
	UPDATE Usuarios
	SET Clave = COALESCE(@CLAVEBASE64, Clave),
		PerfilID = COALESCE(@IDPERFIL, PerfilID),
		FechaUltimaActualizacion = GETDATE(),
		EstadoID = COALESCE(@ESTADOID, EstadoID)
	WHERE UsuarioID = @ID
	
	IF @ESTADOID <> 2 -- INACTIVO
	BEGIN
		SET @MENSAJE = 'Actualización de usuario con ID: ' + CAST(@ID AS VARCHAR);
		-- BITACORA
		EXEC INSERT_BITACORA @USUARIOBITA, 'UPDATE', 'COMPLETADO EXITOSAMENTE', @MENSAJE, @DISPOSITIVO;
	END
	ELSE
	BEGIN
		SET @MENSAJE = 'Desactivación de usuario con ID: ' + CAST(@ID AS VARCHAR);
		-- BITACORA
		EXEC INSERT_BITACORA @USUARIOBITA, 'DEACTIVATE', 'COMPLETADO EXITOSAMENTE', @MENSAJE, @DISPOSITIVO;
	END

	SET @RESULT = 1;
END TRY
BEGIN CATCH
	SET @MENSAJE = 'Mensaje de error:' + ERROR_MESSAGE();
	EXEC INSERT_BITACORA @USUARIOBITA, 'UPDATE', 'NO COMPLETADO', @MENSAJE, @DISPOSITIVO;
	SET @RESULT = 0;
END CATCH
GO